version: "3.6"
services:
    webserver:
        build:
            context: ./bin/webserver
        container_name: "ntus_sias-webserver"
        restart: "on-failure"
        ports:
            - "8100:80"
            - "8443:443"
        links:
            - mysql
        volumes:
            - ${DOCUMENT_ROOT}:/var/www/html
            - ${PHP_INI}:/usr/local/etc/php/php.ini
            - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
            - ${APACHE_LOG_DIR}:/var/log/apache2
    mysql:
        build: ./bin/mysql
        container_name: "ntus_sias-mysql"
        restart: "on-failure"
        ports:
            - "8101:3306"
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
            - ${MYSQL_LOG_DIR}:/var/log/mysql
            - ${MYSQL_INIT_DB}:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "ntus_sias-phpmyadmin"
        restart: "on-failure"
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "8102:80"
        volumes:
            - /sessions
